default:
  logger:
    log_level: "INFO"
  service:
    host: "0.0.0.0"
    port: 8282
    cert_file: "ssl_certs/localhost.crt"
    cert_key: "ssl_certs/localhost.key"
  chat_engine:
    model_root: "models"
    concurrent_limit: 1
    handler_search_path:
      - "src/handlers"
    handler_configs:
      RtcClient:
        module: client/rtc_client/client_handler_rtc
      SileroVad:
        module: vad/silerovad/vad_handler_silero
        speaking_threshold: 0.5
        start_delay: 1024
        end_delay: 1200
        buffer_look_back: 2000
        speech_padding: 256
      SenseVoice:
        enabled: True
        module: asr/siliconflow/asr_handler_siliconflow
        model_name: "FunAudioLLM/SenseVoiceSmall"
        api_url: "https://api.siliconflow.cn/v1/audio/transcriptions"
        api_key: "sk-imybictqelemyvvrugxyhzscehwjilvxwhplzxcbzmtmolpp"
      Volcengine_TTS:
        enabled: True
        module: tts/volcengine_tts/tts_handler_volcengine
        voice: "zh_female_vv_uranus_bigtts"
        resource_id: "seed-tts-2.0"
        app_id: "5044958674"
        access_token: "hEhGD9nEoCmqz2u3mGTPyz8Wr3zZAoZ_"
        sample_rate: 24000
        audio_format: "pcm"
        chunk_flush_bytes: 8000
      LLMOpenAICompatible:
        enabled: True
        module: llm/openai_compatible/llm_handler_openai_compatible
        # api_url: "https://api.siliconflow.cn/v1"
        # api_key: "sk-imybictqelemyvvrugxyhzscehwjilvxwhplzxcbzmtmolpp"
        # model_name: "Qwen/Qwen2.5-7B-Instruct"
        
        model_name: "psy"
        api_url: "http://localhost:8849/v1"
        api_key: "eeee"

        enable_video_input: False
        history_length: 20
        system_prompt: "请你扮演一个 AI 助手，用简短的两三句对话来回答用户的问题，并在对话内容中加入合适的标点符号，不需要讨论标点符号相关的内容"
        
      LiteAvatar:
        module: avatar/liteavatar/avatar_handler_liteavatar
        avatar_name: 20250408/P19U7JIOAP2aeE6kleXLq7IQ
        fps: 25
        debug: false
        enable_fast_mode: false
        use_gpu: true
